# -*- coding: utf-8 -*-
	
# pegar lista y este bucle para añadir ciudades, en cualquier vista
# cambiar la id del pais 	
#for c in lista_colombia:
#	s = City()
#	s.name = c
#	s.country_id='4'
#	s.save()
CH_STATE = [
	u'España',			#id=1
	u'México',			#id=2
	u'Chile',			#id=3
	u'Colombia',		#id=4
	u'Venezuela',		#id=5
	u'Perú',			#id=6
	u'Ecuador',			#id=7
	u'Guatemala',		#id=8
	u'Cuba',			#id=9
	u'Rep. Dominicana',	#id=10
	u'Honduras',		#id=11
	u'Bolivia',			#id=12
	u'El Salvador',		#id=13
	u'Nicaragua',		#id=14
	u'Paraguay',		#id=15
	u'Costa Rica',		#id=16
	u'Panamá',			#id=17
	u'Otro'				#id=18
]

lista_colombia = [

]

lista_chile=[
'Gran Santiagoo',
'Gran Concepción',
'Gran Valparaíso',
'Gran La Serena',
'Antofagasta',
'Gran Temuco',
'Gran Rancagua',
'Gran Iquique',
'Talca',
'Arica',
'Gran Puerto Montt',
'Gran Chillán',
'Los Ángeles',
'Calama',
'Copiapó',
'Osorno',
'Gran Quillota',
'Valdivia',
'Punta Arenas',
'Gran San Antonio',
'Curicó',
'Ovalle',
'Linares',
'Los Andes',
'Melipilla',
'San Felipe'
]

lista_mexi =[
'Ciudad de México',
'Ecatepec',
'Guadalajara',
'Puebla de Zaragoza',
'Ciudad Juárez',
'Tijuana',
'León',
'Zapopan',
'Monterrey',
'Nezahualcóyotl',
'Chihuahua',
'Naucalpan de Juárez',
'Mérida',
'San Luis Potosí',
'Aguascalientes',
'Hermosillo',
'Saltillo',
'Mexicali',
'Culiacán Rosales',
'Guadalupe',
'Acapulco de Juárez',
'Tlalnepantla de Baz',
'Cancún',
'Santiago de Querétaro',
'Chimalhuacán',
'Torreón',
'Morelia',
'Reynosa',
'Tlaquepaque',
'Tuxtla Gutiérrez',
'Victoria de Durango',
'Toluca de Lerdo',
'Ciudad López Mateos',
'Cuautitlán Izcalli',
'Apodaca',
'Heroica Matamoros',
'San Nicolás de los Garza',
'Veracruz',
'Xalapa',
'Tonalá',
'Mazatlán',
'Irapuato',
'Nuevo Laredo',
'Xico',
'Villahermosa',
'General Escobedo',
'Celaya',
'Cuernavaca',
'Tepic',
'Ixtapaluca',
'Ciudad Victoria',
'Ciudad Obregón',
'Tampico',
'Villa Nicolás Romero',
'Ensenada',
'San Francisco Coacalco',
'Santa Catarina',
'Uruapan',
'Gómez Palacio',
'Los Mochis',
'Pachuca de Soto',
'Oaxaca de Juárez',
'Soledad de Graciano Sánchez',
'Tehuacán',
'Ojo de Agua',
'Coatzacoalcos',
'San Francisco de Campeche',
'Monclova',
'La Paz',
'Heroica Nogales',
'Buenavista',
'Puerto Vallarta',
'Tapachula',
'Ciudad Madero',
'San Pablo de las Salinas',
'Chilpancingo de los Bravo',
'Poza Rica de Hidalgo',
'Chicoloapan',
'Ciudad del Carmen',
'Chalco de Díaz Covarrubias',
'Jiutepec',
'Salamanca',
'San Luis Río Colorado',
'San Cristóbal de las Casas',
'Cuautla de Morelos',
'Juárez',
'Chetumal',
'Piedras Negras',
'Playa del Carmen',
'Zamora',
'Córdoba',
'San Juan del Río',
'Colima',
'Ciudad Acuña',
'Manzanillo',
'Zacatecas',
'Veracruz',
'Ciudad Valles',
'Guadalupe',
'San Pedro Garza García',
'Naucalpan de Juárez',
'Fresnillo',
'Orizaba',
'Miramar',
'Iguala',
'Delicias',
'Villa de Álvarez',
'Ciudad Cuauhtémoc',
'Navojoa',
'Guaymas',
'Minatitlán',
'Cuautitlán',
'Texcoco de Mora',
'Hidalgo del Parral',
'Tepexpan',
'Tulancingo de Bravo',
'San Juan Bautista Tuxtepec'
]

lista_ciudades_esp=[
u'Barcelona',
u'Valencia',
u'Sevilla',
u'Zaragoza',
u'Málaga',
u'Murcia',
u'Palma',
u'Las Palmas de Gran Canaria',
u'Bilbao',
u'Alicante',
u'Córdoba',
u'Valladolid',
u'Vitoria-Gasteiz',
u'La Coruña',
u'Granada',
u'Oviedo',
u'Santa Cruz de Tenerife',
u'Pamplona',
u'Almería',
u'Donostia-San Sebastián',
u'Burgos',
u'Albacete Mancha',
u'Santander',
u'Castellón de la Plana',
u'Logroño',
u'Badajoz',
u'Huelva',
u'Salamanca',
u'Lérida',
u'Tarragona',
u'León',
u'Cádiz',
u'Jaén',
u'Orense',
u'Gerona',
u'Lugo',
u'Santiago de Compostela',
u'Cáceres',
u'Melilla',
u'Ceuta',
u'Guadalajara',
u'Toledo',
u'Pontevedra',
u'Palencia',
u'Ciudad Real',
u'Zamora',
u'Mérida',
u'Ávila',
u'Cuenca',
u'Huesca',
u'Segovia',
u'Soria',
u'Teruel']

CH_DOGS = [
	 u'Desconocida',
     u'Affenpinscher',
     u'Airedale Terrier',
     u'Akita americano',
     u'Akita Inu',
     u'Alaskan Malamute',
     u'American Staffordshire Terrier',
     u'Basenji',
     u'Basset Hound',
     u'Beagle',
     u'Beauceron',
     u'Bichon Frise',
     u'Bodeguero',
 	 u'Borzoi',
	 u'Boston Terrier',
 	 u'Bretón',
	 u'Bull Terrier Inglés',
	 u'Bulldog Francés',
 	 u'Bullmastiff',
	 u'Cane Corso',
 	 u'Caniche',
 	 u'Chihuahua',
	 u'Chow Chow',
	 u'Cocker Americano',
	 u'Cocker Spaniel',
 	 u'Collie',
	 u'Collie Barbudo',
 	 u'Collie de la Frontera',
 	 u'Dalmata',
 	 u'Doberman',
	 u'Dogo Argentino',
	 u'Field Spaniel',
	 u'Fox Terrier Chileno',
	 u'Fox Terrier Wire',
	 u'Foxhound Inglés',
	 u'Galgo Español',
	 u'Golden Retrieveer',
	 u'Gran Danés',
 	 u'Hovawart',
	 u'Husky siberiano',
	 u'Irish water spaniel',
	 u'Jack Russell Terrier',
 	 u'Komondor',
	 u'Kritikos Lagonikos',
	 u'Labrador Retriever',
	 u'Lebrel afgano',
 	 u'Leonberger',
 	 u'Maltés',
	 u'Mastín inglés',
 	 u'Mestizo',
	 u'Pastor Alemán',
	 u'Pastor Catalán',
 	 u'Pequinés',
 	 u'Perro de agua español',
	 u'Pinscher Miniatura',
 	 u'Podenco',
 	 u'Pointer',
 	 u'Rottweiler',
 	 u'Samoyedo',
	 u'San Bernardo',
	 u'Schnauzer estándar',
	 u'Schnauzer gigante',
	 u'Schnauzer miniatura',
	 u'Setter Inglés',
	 u'Shar Pei',
	 u'Shiba Inu',
	 u'Shih Tzu',
	 u'Terrier Irlandés',
 	 u'West Highland White Terrier',
 	 u'Whippet',
	 u'Yorkshire Terrier',
 	 u'Otra'
	]

r_gatos = [
'Abisinio',
'American shorthair',
'American wirehair',
'Angora turco',
'Azul ruso',
'Gato balinés',
'Bengala',
'Burmés',
'Bobtail japonés',
'Bombay',
'Bosque de Noruega',
'British Shorthair',
'Burmilla',
'California Spangled',
'Chantilly-Tiffany',
'Chartreux',
'Gato color point',
'Cornish rex',
'Curl Americano',
'Devon rex',
'Don Sphynx',
'Dragon Li',
'Gato común europeo',
'Gato exótico',
'Gato FoldEx',
'Gato Skookum',
'German Rex',
'Habana brown',
'Gato himalayo',
'Khao Manee',
'Korat',
'Maine Coon',
'Gato Manx',
'Mau egipcio',
'Munchkin',
'Ocicat',
'Gato oriental',
'Gato oriental de pelo largo',
'Gato persa',
'Ragdoll',
'Sagrado de Birmania',
'Scottish Fold',
'Selkirk rex',
'Gato seychellois',
'Gato siamés',
'Siamés moderno',
'Siamés Red Point',
'Siamés tradicional',
'Siberiano',
'Snowshoe',
'Sokoke',
'Sphynx',
'Gato tonkinés',
'Gato Van Turco'
]