# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-04 16:03
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalimage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='images'),
        ),
    ]
