# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-11 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0002_auto_20180404_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races', to='animales.Race', verbose_name='Raza'),
        ),
    ]
