# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-11 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0003_animal_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.CharField(help_text='Por ejemplo: 2 meses', max_length=200, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='color',
            field=models.CharField(help_text='Por ejemplo: Marr\xf3n y Negro', max_length=200, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='genre',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra'), ('Otro', 'Otro')], default='Otro', max_length=200, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='animales.AnimalImage', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='animales.Profile', verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='state',
            field=models.CharField(choices=[('Adopci\xf3n', 'Adopci\xf3n'), ('Perdido', 'Perdido'), ('Encontrado', 'Encontrado'), ('Acogida', 'Acogida'), ('Otro', 'Otro')], default='Otro', max_length=200, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type_animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='animales.AnimalType', verbose_name='Tipo de Animal'),
        ),
    ]
