# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-12 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0004_auto_20180411_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil de usuario', 'verbose_name_plural': 'Perfiles de usuario'},
        ),
        migrations.RemoveField(
            model_name='animal',
            name='image',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='race',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='type_animal',
        ),
        migrations.RemoveField(
            model_name='animalimage',
            name='alt',
        ),
        migrations.AddField(
            model_name='animalimage',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='animales.Animal', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='animaltype',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='animales.Animal', verbose_name='Tipo de Animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='animales.Profile', verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='race',
            name='type_animal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='races', to='animales.AnimalType', verbose_name='Tipo de Animal'),
        ),
    ]
