# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-12 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0006_auto_20180412_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animales'},
        ),
        migrations.AlterModelOptions(
            name='animalimage',
            options={'verbose_name': 'Im\xe1gen', 'verbose_name_plural': 'Im\xe1genes'},
        ),
        migrations.AlterModelOptions(
            name='animaltype',
            options={'verbose_name': 'Tipo de Animal', 'verbose_name_plural': 'Tipos de Animales'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Pa\xeds', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'verbose_name': 'Raza', 'verbose_name_plural': 'Razas'},
        ),
    ]
