# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-23 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0007_auto_20180412_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='citiesP', to='animales.City', verbose_name='Ciudad'),
            preserve_default=False,
        ),
    ]
